# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
    ]
