# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160304_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='change_this_default_val', max_length=50),
            preserve_default=False,
        ),
    ]
