# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.CharField(default='default_email', max_length=50),
            preserve_default=False,
        ),
    ]
