# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_name', models.CharField(max_length=200)),
                ('lookup_symbol', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
